import ReduxProvider from '@/lib/redux/redux-provider'
import '@/styles/globals.scss'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <ReduxProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Toaster position='top-center' />
        </body>
      </ReduxProvider>
    </html>
  )
}
