import ReduxProvider from '@/lib/redux/redux-provider'
import '@/styles/globals.scss'
import { getCommonDict } from '@/utils/i18n/get-dictionary'
import { Poppins } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const poppins = Poppins({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children, params: { lang } }) {
  const t = await getCommonDict(lang)
  return (
    <html lang='en'>
      <ReduxProvider>
        <body className={poppins.className}>
          {children}
          <Toaster position='top-center' />
          <div id='modal-container' />
        </body>
      </ReduxProvider>
    </html>
  )
}
