import Navbar from '@/components/common/Navbar'
import ReduxProvider from '@/lib/redux/redux-provider'
import '@/styles/globals.scss'
import { getCommonDict } from '@/utils/i18n/get-dictionary'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children, params: { lang } }) {
  const t = await getCommonDict(lang)
  return (
    <html lang='en'>
      <ReduxProvider>
        <body className={inter.className}>
          <Navbar t={t.header} />
          <main className='mt-20'>{children}</main>
          <Toaster position='top-center' />
        </body>
      </ReduxProvider>
    </html>
  )
}
